#!/bin/sh
# frontend/netlify-build.sh — the ONLY "build step" this frontend has, and it
# is not a bundler: frontend/config.js is gitignored (it carries the API
# token — see config.example.js), so a git-based Netlify deploy has no
# config.js to publish. This script generates one from two Netlify site
# environment variables at deploy time, so the token never touches git.
#
# Netlify site settings that call this (see docs/API.md "Netlify
# preparation" for the full picture):
#   Base directory:      frontend
#   Build command:       sh netlify-build.sh
#   Publish directory:   frontend   (or "." if base directory is "frontend")
#   Environment variables (Site settings -> Environment variables):
#     DASHBOARD_API_BASE_URL = https://tradingbotapi.bhardwajvaibhav.com
#     DASHBOARD_API_TOKEN    = <the same value as deploy/api.env's
#                               DASHBOARD_API_TOKEN on the VPS>
#
# Local development is unaffected — this script only runs on Netlify;
# `cp config.example.js config.js` (docs/API.md §2) is still how you set up
# local dev, and that config.js is never touched by this script.

set -eu

: "${DASHBOARD_API_BASE_URL:?DASHBOARD_API_BASE_URL is not set in this Netlify site's environment variables}"
: "${DASHBOARD_API_TOKEN:?DASHBOARD_API_TOKEN is not set in this Netlify site's environment variables}"

cat > config.js <<EOF
// GENERATED by netlify-build.sh at deploy time from this Netlify site's
// environment variables — do not edit by hand, and this file is never
// committed to git (see .gitignore). Local dev uses config.example.js's
// copy-and-edit flow instead (docs/API.md §2).
window.DASHBOARD_CONFIG = {
  apiBaseUrl: "${DASHBOARD_API_BASE_URL}",
  apiToken: "${DASHBOARD_API_TOKEN}",
  pollIntervalMs: 15000,
};
EOF

echo "netlify-build.sh: generated config.js for ${DASHBOARD_API_BASE_URL}"
